# Generated by Django 5.1.2 on 2024-10-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nobre_usuario', models.CharField(max_length=255)),
            ],
        ),
    ]
