# Generated by Django 5.1.2 on 2024-10-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fk_generos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.generos'),
        ),
    ]
